import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './Navbar'
import AuthProvider from './auth/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: '...',
    description: '...'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <AuthProvider>
      <body className={inter.className}>
        <NavBar/>
        <main className='p-5'>
          {children}
        </main></body>
        </AuthProvider>
    </html>
  )
}
